### ISSUE TITLE
Default length missing in the man page

### ISSUE THREAD

**Issue by frispete** [spkr-beep/beep#11]
Hi,

just wanted to drop a note, that I enjoy this since a day or so. Thank you very much.

I've packaged it for openSUSE [here](https://build.opensuse.org/package/show/home:frispete:Tumbleweed/beep) and attempt to submit this to the official channels.

I've found one nitpick: the default length isn't documented in the man page, as well as not any default is noted in --help. Both would be nice.

Anyway, great work.

**Comment by ndim** [comment]
Thanks for the report. I will be looking into this later, probably this weekend.

**Comment by ndim** [comment]
Feel free to reopen this if I have overlooked something.
