### ISSUE TITLE
The check for running under sudo can be circumvented

### ISSUE THREAD

**Issue by Ropid** [spkr-beep/beep#7]
I'm wondering if the way 'beep' checks for 'sudo' can be improved. Checking for "SUDO_..." environment variables seems too simple. For example the following makes 'beep' run without complaining:

    sudo env --unset=SUDO_{GID,COMMAND,USER,UID} beep

or:

    sudo env -i beep

Maybe one way to do it instead would be to go through parent processes to find if 'sudo' is involved anywhere in the process tree? Hopefully the 'sudo' process name wouldn't be easily changed unlike the environment?

Here's some more alternatives besides 'env' to change the environment and run 'beep':

    sudo bash -c 'unset SUDO_{UID,GID,COMMAND,USER}; beep'
    sudo perl -e 'map { delete $ENV{$_} } grep /^SUDO_/, keys %ENV; exec "beep"'
    sudo perl -e 'undef %ENV; exec "beep"'
    sudo awk 'BEGIN{ for (x in ENVIRON) { if (x ~ /^SUDO_/) { delete ENVIRON[x] } } system("beep") }'

**Comment by ndim** [comment]
Thank you very much for explicitly explaining how one would get rid of the `SUDO_` variables.

Let me first explain why I think neither of those ways to trick new beep's sudo detection is an issue, and then tell me where I am wrong.

Old beep needed to run as root. Two popular ways to achieve that (also used and propagated by some distro packages) was to install beep as setuid-root or to run beep via sudo with something like `alias beep="sudo /usr/bin/beep"` and an adapted `/etc/sudoers` config file. So old installations (manual installation from source or from distro binary packages) used one of these ways to have non-root users run `beep`.

New beep does not require root, but if someone installs new beep into an older system with any of the old setuid or sudo setups, new beep will tell the user to fix their old setup by refusing to run.

I cannot imagine why anybody would have set up their systems for old beep by having `sudo` configured to run `bash`, `perl`, or `env` as root for any user.

So existing old setups should be caught by new beep, and if anybody had their system configured to allow some users to run `bash`, `env`, or `perl` as root, that goes beyond `beep`s responsibility.

If people insist hard enough on shooting themselves in their foot, there is no way we can prevent them.

That is my reasoning so far. Please tell me where I am wrong. I have been wrong in the past, and will be wrong in the future, but right now I fail to see where my reasoning in this case might be wrong.

**Comment by ndim** [comment]
Thank you for pointing towards the lack of documentation on the purpose of these checks.

With the explanations I have made in this issue, I have improved the comment on the checks in the source code to make their purpose clearer for everybody else but their author (i.e. myself).

Please feel free to reopen this if you feel this has been solved inadequately.

**Comment by Ropid** [comment]
Yes, I agree the new source code comments explain what's going on well and resolve this issue here. I had previously misunderstood what the point beep's behavior was really about.

**Comment by ndim** [comment]
Sorry for not having that clarifying comment in there from the beginning. That could have saved you some time and effort.
